import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import { UserProvider } from "@auth0/nextjs-auth0/client";
import { Toaster } from "@/lib/reactHotToastExports";
import Footer from "@/components/Footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <UserProvider>
        <body className={inter.className}>
          <Navbar />
          <div
            style={{
              minHeight: "calc(100vh - 72px - 96px)",
              overflowY: "auto",
            }}
          >
            {children}
            <Toaster
              containerStyle={{
                top: 70,
              }}
            />
          </div>
          <Footer />
        </body>
      </UserProvider>
    </html>
  );
}
